linters:
  enable:
    - errcheck
    - dupl

linters-settings:
  errcheck:
    exclude-functions:
      - fmt.Print
      - fmt.Printf
      - fmt.Println
      - fmt.Fprint
      - fmt.Fprintf
      - fmt.Fprintln
  dupl:
    threshold: 100
