services:
  sing-box:
    build:
      context: ..
      dockerfile: transit/Dockerfile
    container_name: sing-box
    restart: always
    network_mode: host
    env_file: .env
    volumes:
      - ../transit_config.tmpl.json:/transit_config.tmpl.json
      - /etc/localtime:/etc/localtime:ro