services:
  sing-box:
    build: .
    container_name: sing-box
    restart: always
    network_mode: host
    env_file: .env
    volumes:
      - ./config.template.json:/config.template.json
      - /etc/localtime:/etc/localtime:ro